### ISSUE TITLE
Trigger server to re-parse on reload

### ISSUE THREAD

**Issue by elextr** [techee/geany-lsp#32] opened 2023-12-13 00:15 UTC
Pulled b4n's latest encodings changes and mesoned them but had `encodings.c` open at the time.  Got a reload info bar as expected, selected reload and then the positioning of semantic highlighting is wrong.  Looks like clangd is still using its cache and not reparsing the modified file or the plugin isn't updating semantics in Scintilla.

**Comment by elextr** [comment] 2023-12-13 00:28
After some more experimentation:

1. after the reload no semantics are shown, or semantics are shown in the wrong position, I couldn't determine what controlled that.
2. switching tabs away and back has no effect
3. restarting the server (`Tools->LSP Client->Restart all servers`) has no effect
4. restarting the server and switching tabs away and back shows semantics correctly again

**Comment by elextr** [comment] 2024-03-08 23:41
Will do, but it will be a while before I am home to that machine.

**Comment by techee** [comment] 2024-08-09 20:37
Should be fixed so closing - if the issue is still present, please reopen it.

**Closed by techee** 2024-08-09 20:37 UTC
